name: warmup me
on:
  schedule:
    - cron: "*/3 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: http://api.gamstagram.com/
